---
title: "Module2_0"
author: "AdrienM"
date: "2026-05-21"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
title: "Workshop2_Intro"
author: "AdrienM"
date: "2026-05-20"
output:
  word_document: default
  html_document: default
  pdf_document: default
---

#New chunk shortcuts 

Comd + opt I 
Crtl + Alt I 

```{r}
library(tidyverse)
```

```{r}
mpg
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, colour = class))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, size = class))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, alpha = class))
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), color = "blue")
```

```{r}
library(ggplot2)

ggplot(data = mpg) +
  geom_point(
    mapping = aes(
      x = displ,
      y = hwy,
      colour = displ < 5
    )
  )
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_wrap(~ class, nrow = 2)
```

```{r}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) + 
  facet_grid(drv ~ cyl)
```

